import '../app/product_definition.dart';

/// Maps generated AutoRoute names to the [AppModule] that must be enabled.
///
/// Routes omitted here are treated as shared platform routes (auth, help, chat,
/// enlist helpers) and are allowed on every product.
AppModule? moduleForRouteName(String routeName) {
  return _routeModules[routeName];
}

const Map<String, AppModule> _routeModules = {
  // Registration / front desk
  'FrontDeskDashboardRoute': AppModule.registration,
  'PendingDeviceApprovalsRoute': AppModule.registration,
  'PatientDevicesRoute': AppModule.registration,
  'FamilyLinksRoute': AppModule.registration,
  'PatientListRoute': AppModule.registration,
  'PatientFormRoute': AppModule.registration,
  'PatientChartSelectRoute': AppModule.registration,
  'PatientChartRoute': AppModule.registration,
  'PatientHubSearchRoute': AppModule.registration,
  'PatientHubRoute': AppModule.registration,
  'AppointmentListRoute': AppModule.registration,
  'AppointmentRequestsRoute': AppModule.registration,
  'TodayPatientsRoute': AppModule.registration,
  'NewAppointmentRoute': AppModule.registration,
  'NewPatientRoute': AppModule.registration,

  // Billing / payments / service catalog
  'PendingBillsRoute': AppModule.billing,
  'BillingDashboardRoute': AppModule.billing,
  'ReceivablesHmoRoute': AppModule.billing,
  'ReceivablesDiscountRoute': AppModule.billing,
  'DiscountPolicyManagementRoute': AppModule.billing,
  'ClinicalPackageManagementRoute': AppModule.billing,
  'TransactionsRoute': AppModule.billing,
  'SystemSetupRoute': AppModule.billing,
  'BankManagementRoute': AppModule.billing,
  'ConsultingRoomsRoute': AppModule.billing,
  'WardManagementRoute': AppModule.billing,
  'AnnouncementManagementRoute': AppModule.administration,
  'EnlistServiceRoute': AppModule.billing,
  'RenderServiceRoute': AppModule.billing,
  'ViewServiceRoute': AppModule.billing,
  'AddServiceRoute': AppModule.billing,
  'AddCategoryRoute': AppModule.billing,
  'AddDepartmentRoute': AppModule.billing,
  'InpatientBillsListRoute': AppModule.billing,
  'PatientBillingAccountRoute': AppModule.billing,
  'BillingWardInpatientsRoute': AppModule.billing,
  'AwaitingBillingClearanceRoute': AppModule.billing,
  'PatientBillingRoute': AppModule.billing,
  'PatientWalletHistoryRoute': AppModule.billing,

  // Pharmacy
  'PharmacyDashboardRoute': AppModule.pharmacy,
  'PharmacyHeadDashboardRoute': AppModule.pharmacy,
  'PharmacyReportsHubRoute': AppModule.pharmacy,
  'PharmacySalesBreakdownRoute': AppModule.pharmacy,
  'PharmacySalesBreakdownDetailRoute': AppModule.pharmacy,
  'PharmacyInventoryValuationRoute': AppModule.pharmacy,
  'MedicineInventoryRoute': AppModule.pharmacy,
  'AddDrugRoute': AppModule.pharmacy,
  'AddSupplierRoute': AppModule.pharmacy,
  'AddBatchRoute': AppModule.pharmacy,
  'BatchesPreviewWardPricingRoute': AppModule.pharmacy,
  'StockTransferRoute': AppModule.pharmacy,
  'CreateRequisitionRoute': AppModule.pharmacy,
  'SupplyHistoryRoute': AppModule.pharmacy,
  'DispenseHistoryRoute': AppModule.pharmacy,
  'PharmacyLocationRoute': AppModule.pharmacy,
  'PharmacyPOSRoute': AppModule.pharmacy,
  'DispenseRoute': AppModule.pharmacy,
  'MedicationRequestsRoute': AppModule.pharmacy,
  'PharmacyRefillRequestsRoute': AppModule.pharmacy,
  'WaitingPatientRoute': AppModule.pharmacy,
  'PurchaseItemSalesRoute': AppModule.pharmacy,

  // Laboratory
  'LabDashboardRoute': AppModule.laboratory,
  'LabInvestigationsRoute': AppModule.laboratory,
  'LabConfigRoute': AppModule.laboratory,
  'LabCreateOrderRoute': AppModule.laboratory,
  'LabOrderDetailRoute': AppModule.laboratory,
  'LabResultEntryRoute': AppModule.laboratory,
  'HubLabsRoute': AppModule.laboratory,

  // Radiology
  'RadiologyDashboardRoute': AppModule.radiology,
  'RadiologyInvestigationsRoute': AppModule.radiology,
  'RadiologyWorklistRoute': AppModule.radiology,
  'RadiologyCreateRequestRoute': AppModule.radiology,
  'RadiologyRequestDetailRoute': AppModule.radiology,
  'RadiologyPatientHistoryRoute': AppModule.radiology,
  'HubImagingRoute': AppModule.radiology,

  // Nursing
  'NursesDashboardRoute': AppModule.nursing,
  'NursingRosterRoute': AppModule.nursing,
  'NursingAssignmentsRoute': AppModule.nursing,
  'NurseConsumableUsageRoute': AppModule.nursing,
  'WaitingPatientsRoute': AppModule.nursing,
  'InpatientsListRoute': AppModule.nursing,
  'AwaitingNursesClearanceRoute': AppModule.nursing,
  'InpatientPatientViewRoute': AppModule.nursing,
  'InpatientOverviewRoute': AppModule.nursing,
  'InpatientVitalsRoute': AppModule.nursing,
  'InpatientMedicationsRoute': AppModule.nursing,
  'InpatientIVRoute': AppModule.nursing,
  'InpatientIORoute': AppModule.nursing,
  'InpatientNotesRoute': AppModule.nursing,
  'InpatientWoundAssessmentRoute': AppModule.nursing,
  'InpatientWardRoundTab': AppModule.nursing,
  'InpatientProceduresRoute': AppModule.nursing,
  'InpatientCarePlanRoute': AppModule.nursing,
  'InpatientMonitoringRoute': AppModule.nursing,
  'InpatientLabResultsRoute': AppModule.nursing,
  'InpatientAlertsRoute': AppModule.nursing,
  'InpatientHandoverRoute': AppModule.nursing,

  // Physician / clinical
  'DoctorDashboardRoute': AppModule.physician,
  'DoctorOutpatientListRoute': AppModule.physician,
  'DoctorOngoingEncountersRoute': AppModule.physician,
  'DoctorWalkInQueueRoute': AppModule.physician,
  'DoctorWaitingPatientsRoute': AppModule.physician,
  'DoctorEmergencyStartRoute': AppModule.physician,
  'EdBoardRoute': AppModule.physician,
  'EdEmergencyRequestsRoute': AppModule.physician,
  'EdEmergencyRequestDetailRoute': AppModule.physician,
  'EdRegistrationRoute': AppModule.physician,
  'EdTriageRoute': AppModule.physician,
  'WardRoundsRoute': AppModule.physician,
  'DoctorPendingLabsRoute': AppModule.physician,
  'DoctorPendingImagingRoute': AppModule.physician,
  'DoctorPendingPrescriptionsRoute': AppModule.physician,
  'DoctorCompletedEncountersRoute': AppModule.physician,
  'ConsultationPaymentReportRoute': AppModule.physician,
  'HospitalReportsHubRoute': AppModule.medicalRecords,
  'HospitalReportRoute': AppModule.medicalRecords,
  'HealthCampaignsAdminRoute': AppModule.medicalRecords,
  'HealthNewsAdminRoute': AppModule.medicalRecords,
  'EncounterEditHistoryDetailRoute': AppModule.physician,
  'DoctorTemplatesRoute': AppModule.physician,
  'DoctorProfileRoute': AppModule.physician,
  'DoctorCompletedEncounterViewRoute': AppModule.physician,
  'CompletedEncounterSummaryTab': AppModule.physician,
  'CompletedEncounterHistoryTab': AppModule.physician,
  'CompletedEncounterExaminationTab': AppModule.physician,
  'CompletedEncounterNotesTab': AppModule.physician,
  'CompletedEncounterDiagnosisTab': AppModule.physician,
  'CompletedEncounterLabsTab': AppModule.physician,
  'CompletedEncounterImagingTab': AppModule.physician,
  'CompletedEncounterSurgeryTab': AppModule.physician,
  'CompletedEncounterPrescriptionsTab': AppModule.physician,
  'CompletedEncounterAppointmentsTab': AppModule.physician,
  'CompletedEncounterFollowUpTab': AppModule.physician,
  'DoctorEncounterViewRoute': AppModule.physician,
  'DoctorEncounterChartTab': AppModule.physician,
  'DoctorEncounterHistoryTab': AppModule.physician,
  'DoctorEncounterExaminationTab': AppModule.physician,
  'DoctorEncounterDiagnosisTab': AppModule.physician,
  'DoctorEncounterInvestigationsTab': AppModule.physician,
  'DoctorEncounterImagingTab': AppModule.physician,
  'DoctorEncounterSurgeryTab': AppModule.physician,
  'DoctorEncounterPrescriptionTab': AppModule.physician,
  'DoctorEncounterProceduresTab': AppModule.physician,
  'DoctorEncounterNotesTab': AppModule.physician,
  'DoctorEncounterAdmissionTab': AppModule.physician,
  'DoctorEncounterFollowUpTab': AppModule.physician,
  'ObstetricsDashboardRoute': AppModule.physician,
  'ObstetricsPatientSelectRoute': AppModule.physician,
  'ObstetricsPregnanciesListRoute': AppModule.physician,
  'ObstetricsPregnancyViewRoute': AppModule.physician,
  'ObstetricsPregnancyOverviewTab': AppModule.physician,
  'ObstetricsAntenatalVisitsTab': AppModule.physician,
  'ObstetricsPregnancyClinicalOrdersTab': AppModule.physician,
  'ObstetricsPregnancyClinicalResultsTab': AppModule.physician,
  'ObstetricsLabourDeliveryTab': AppModule.physician,
  'ObstetricsPostnatalTab': AppModule.physician,
  'ObstetricsAddPregnancyRoute': AppModule.physician,
  'ObstetricsAddAntenatalVisitRoute': AppModule.physician,
  'ObstetricsEditAntenatalVisitRoute': AppModule.physician,
  'ObstetricsAddLabourDeliveryRoute': AppModule.physician,
  'ObstetricsLabourDeliveryViewRoute': AppModule.physician,
  'ObstetricsAddPartogramEntryRoute': AppModule.physician,
  'ObstetricsAddBabyRoute': AppModule.physician,
  'ObstetricsEditBabyRoute': AppModule.physician,
  'ObstetricsRegisterBabyRoute': AppModule.physician,
  'ObstetricsPostnatalListRoute': AppModule.physician,
  'ObstetricsAddPostnatalVisitRoute': AppModule.physician,
  'ObstetricsGynaeProceduresRoute': AppModule.physician,
  'ObstetricsAddGynaeProcedureRoute': AppModule.physician,
  'ObstetricsEditGynaeProcedureRoute': AppModule.physician,

  // Purchases
  'PurchasesInventoryRoute': AppModule.purchases,
  'PurchasesAddItemRoute': AppModule.purchases,
  'PurchasesAddSupplierRoute': AppModule.purchases,
  'PurchasesAddPurchaseRoute': AppModule.purchases,
  'PurchasesStockTransferRoute': AppModule.purchases,
  'PurchasesTransferHistoryRoute': AppModule.purchases,
  'PurchasesPurchaseHistoryRoute': AppModule.purchases,
  'PurchasesLocationRoute': AppModule.purchases,
  'PurchasesRequisitionHistoryRoute': AppModule.purchases,
  'PurchasesUsageHistoryRoute': AppModule.purchases,
  'PurchasesDashboardRoute': AppModule.purchases,

  // Dialysis
  'DialysisDashboardRoute': AppModule.dialysis,
  'DialysisSelectPatientRoute': AppModule.dialysis,
  'DialysisPatientEncountersRoute': AppModule.dialysis,
  'DialysisCreateSessionRoute': AppModule.dialysis,
  'DialysisSessionDetailRoute': AppModule.dialysis,
  'HubDialysisRoute': AppModule.dialysis,

  // Theatre
  'TheatreDashboardRoute': AppModule.theatre,
  'TheatreScheduleFormRoute': AppModule.theatre,
  'TheatreCaseDetailRoute': AppModule.theatre,
  'TheatreRoomsRoute': AppModule.theatre,
  'HubTheatreRoute': AppModule.theatre,

  // Store
  'StoreDashboardRoute': AppModule.store,
  'StoreCategoriesRoute': AppModule.store,
  'StoreItemsRoute': AppModule.store,
  'StoreLocationsRoute': AppModule.store,
  'StoreStockRoute': AppModule.store,
  'StoreMovementsRoute': AppModule.store,
  'StoreAnalyticsRoute': AppModule.store,
  'StoreConsumablesCatalogRoute': AppModule.store,
  'StoreConsumableAnalyticsRoute': AppModule.store,
  'StoreConsumableDetailRoute': AppModule.store,

  // Accounting
  'AccountsDashboardRoute': AppModule.accounting,
  'AccountsRevenueSummaryRoute': AppModule.accounting,
  'AccountsDailyCollectionsRoute': AppModule.accounting,
  'AccountsAgingReportRoute': AppModule.accounting,
  'AccountsFinancialReportsHubRoute': AppModule.accounting,
  'AccountsProfitLossRoute': AppModule.accounting,
  'AccountsCashFlowRoute': AppModule.accounting,
  'AccountsRevenueByServiceRoute': AppModule.billing,
  'AccountsRevenueByServiceDetailRoute': AppModule.billing,
  'AccountsExpenseVsBudgetRoute': AppModule.accounting,
  'AccountsCollectionEfficiencyRoute': AppModule.accounting,
  'AccountsPeriodComparisonRoute': AppModule.accounting,
  'AccountsPaymentMixRoute': AppModule.accounting,
  'AccountsAuditLogRoute': AppModule.accounting,
  'AccountsComplianceRoute': AppModule.accounting,
  'AccountsInvoiceChangesRoute': AppModule.accounting,
  'AccountsLeakDetectionRoute': AppModule.accounting,
  'AccountsStaffActivityRoute': AppModule.accounting,
  'AccountsRefundHistoryRoute': AppModule.accounting,
  'AccountsWalletsOverviewRoute': AppModule.accounting,
  'AccountsDailyCashReconRoute': AppModule.accounting,
  'AccountsBankReconRoute': AppModule.accounting,
  'AccountsApprovalsRoute': AppModule.accounting,
  'AccountsRefundRequestsRoute': AppModule.billing,
  'AccountsPeriodCloseRoute': AppModule.accounting,
  'AccountsJournalEntriesRoute': AppModule.accounting,
  'AccountsChartOfAccountsRoute': AppModule.accounting,
  'AccountsBanksRoute': AppModule.accounting,
  'ReceivablesAnalyticsRoute': AppModule.accounting,

  // HMO
  'HmoListRoute': AppModule.hmo,
  'HmoDetailRoute': AppModule.hmo,
  'HmoFormRoute': AppModule.hmo,
  'HmoServicePricingRoute': AppModule.hmo,

  // Medical records extras (beyond shared patient registration)
  // ConsultationPaymentReport is physician-adjacent; chart remains registration.

  // ICT
  'DashboardRoute': AppModule.ict,

  // Administration / CMD / CMAC / super admin
  'SuperAdminHubRoute': AppModule.administration,
  'CMDDashboardRoute': AppModule.administration,
  'CMDHospitalOverviewRoute': AppModule.administration,
  'CMDFinancialCommandRoute': AppModule.administration,
  'CMDStaffOversightRoute': AppModule.administration,
  'CMDBedsFacilitiesRoute': AppModule.administration,
  'CMDLabMonitoringRoute': AppModule.administration,
  'CMDAlertsIncidentsRoute': AppModule.administration,
  'CMDReportsAnalyticsRoute': AppModule.administration,
  'CMDAuditComplianceRoute': AppModule.administration,
  'CMDCommunicationCenterRoute': AppModule.administration,
  'CustomPatientPushRoute': AppModule.administration,
  'CMDPatientExperienceRoute': AppModule.administration,
  'CMDSystemControlRoute': AppModule.administration,
  'CmacOverviewRoute': AppModule.administration,
  'CmacInsightsRoute': AppModule.administration,
  'CmacPatientActivityRoute': AppModule.administration,
  'CmacClinicalRoute': AppModule.administration,
  'CmacLaboratoryRoute': AppModule.administration,
  'CmacPharmacyRoute': AppModule.administration,
  'CmacOperationsRoute': AppModule.administration,
  'CmacQualityRoute': AppModule.administration,
  'CmacStaffRoute': AppModule.administration,
  'CmacQualitySafetyHubRoute': AppModule.administration,
  'CmacQualityReferralsRoute': AppModule.administration,
  'CmacQualityComplaintsRoute': AppModule.administration,
  'CmacQualityIncidentsRoute': AppModule.administration,
  'CmacQualityInfectionsRoute': AppModule.administration,
  'CmacQualityDetailRoute': AppModule.administration,

  // Hub tabs that are meds-related stay pharmacy-adjacent
  'HubMedsRoute': AppModule.pharmacy,
};
