import 'package:auto_route/auto_route.dart';
import 'package:helty/app_router.gr.dart';
import 'package:helty/src/core/guards/auth_guard.dart';

@AutoRouterConfig(replaceInRouteName: 'Screen|Page,Route')
class AppRouter extends RootStackRouter {
  @override
  RouteType get defaultRouteType => RouteType.material();

  @override
  List<AutoRoute> get routes => [
    // ── Auth routes (no guard) ───────────────────────────────────────
    AutoRoute(page: LoginRoute.page, initial: true),
    AutoRoute(page: RegisterRoute.page),
    AutoRoute(page: ForgotPasswordRoute.page),
    AutoRoute(page: ResetPasswordRoute.page),

    // ── Protected shell ──────────────────────────────────────────────
    AutoRoute(
      page: HomeRoute.page,
      guards: [const AuthGuard()],
      children: [
        AutoRoute(page: SuperAdminHubRoute.page),
        AutoRoute(page: SuperAdminStaffListRoute.page),
        AutoRoute(page: SuperAdminStaffDetailRoute.page),
        AutoRoute(page: CMDDashboardRoute.page, initial: true),
        AutoRoute(page: CMDHospitalOverviewRoute.page),
        AutoRoute(page: CMDFinancialCommandRoute.page),
        AutoRoute(page: CMDStaffOversightRoute.page),
        AutoRoute(page: CMDBedsFacilitiesRoute.page),
        AutoRoute(page: CMDLabMonitoringRoute.page),
        AutoRoute(page: CMDAlertsIncidentsRoute.page),
        AutoRoute(page: CMDReportsAnalyticsRoute.page),
        AutoRoute(page: CMDAuditComplianceRoute.page),
        AutoRoute(page: CMDCommunicationCenterRoute.page),
        AutoRoute(page: CMDPatientExperienceRoute.page),
        AutoRoute(page: CMDSystemControlRoute.page),
        AutoRoute(page: CmacOverviewRoute.page),
        AutoRoute(page: CmacInsightsRoute.page),
        AutoRoute(page: CmacPatientActivityRoute.page),
        AutoRoute(page: CmacClinicalRoute.page),
        AutoRoute(page: CmacLaboratoryRoute.page),
        AutoRoute(page: CmacPharmacyRoute.page),
        AutoRoute(page: CmacOperationsRoute.page),
        AutoRoute(page: CmacQualityRoute.page),
        AutoRoute(page: CmacStaffRoute.page),
        AutoRoute(page: CmacQualitySafetyHubRoute.page),
        AutoRoute(page: CmacQualityReferralsRoute.page),
        AutoRoute(page: CmacQualityComplaintsRoute.page),
        AutoRoute(page: CmacQualityIncidentsRoute.page),
        AutoRoute(page: CmacQualityInfectionsRoute.page),
        AutoRoute(
          path: 'cmac/quality/:entity/:recordId',
          page: CmacQualityDetailRoute.page,
        ),
        AutoRoute(page: FrontDeskDashboardRoute.page),
        AutoRoute(page: PatientListRoute.page),
        AutoRoute(page: PatientFormRoute.page),
        AutoRoute(page: PatientChartSelectRoute.page),
        AutoRoute(page: PatientChartRoute.page),
        AutoRoute(page: PatientHubSearchRoute.page),
        AutoRoute(
          page: PatientHubRoute.page,
          children: [
            AutoRoute(page: HubOverviewRoute.page, initial: true),
            AutoRoute(page: HubProfileRoute.page),
            AutoRoute(page: HubEncountersRoute.page),
            AutoRoute(page: HubVitalsRoute.page),
            AutoRoute(page: HubLabsRoute.page),
            AutoRoute(page: HubImagingRoute.page),
            AutoRoute(page: HubMedsRoute.page),
            AutoRoute(page: HubDialysisRoute.page),
            AutoRoute(page: HubTheatreRoute.page),
            AutoRoute(page: HubDocumentsRoute.page),
            AutoRoute(page: HubNotesRoute.page),
          ],
        ),
        AutoRoute(page: AppointmentListRoute.page),
        AutoRoute(page: TodayPatientsRoute.page),
        AutoRoute(page: PendingBillsRoute.page),
        AutoRoute(page: EnlistServiceRoute.page),
        AutoRoute(page: RenderServiceRoute.page),
        AutoRoute(page: ViewServiceRoute.page),
        // helper screens for creating new entities
        AutoRoute(page: AddServiceRoute.page),
        AutoRoute(page: AddCategoryRoute.page),
        AutoRoute(page: AddDepartmentRoute.page),
        AutoRoute(page: RegisterRoute.page),
        AutoRoute(page: EnlistPaitientRoute.page),
        AutoRoute(page: NewAppointmentRoute.page),
        AutoRoute(page: NotAvailableRoute.page),

        AutoRoute(page: NewPatientRoute.page),
        AutoRoute(page: BillingDashboardRoute.page),
        AutoRoute(page: ReceivablesHmoRoute.page),
        AutoRoute(page: ReceivablesDiscountRoute.page),
        AutoRoute(page: DiscountPolicyManagementRoute.page),
        AutoRoute(page: TransactionsRoute.page),
        AutoRoute(page: SystemSetupRoute.page),
        AutoRoute(page: BankManagementRoute.page),
        AutoRoute(page: NursesDashboardRoute.page),
        AutoRoute(page: NursingRosterRoute.page),
        AutoRoute(page: NursingAssignmentsRoute.page),
        AutoRoute(page: NurseConsumableUsageRoute.page),
        AutoRoute(page: WaitingPatientsRoute.page),
        AutoRoute(page: ConsultingRoomsRoute.page),
        AutoRoute(page: DoctorDashboardRoute.page),
        AutoRoute(page: DoctorOutpatientListRoute.page),
        AutoRoute(page: DoctorOngoingEncountersRoute.page),
        AutoRoute(page: DoctorWalkInQueueRoute.page),
        AutoRoute(page: DoctorEmergencyStartRoute.page),
        AutoRoute(page: EdBoardRoute.page),
        AutoRoute(page: EdRegistrationRoute.page),
        AutoRoute(page: EdTriageRoute.page),
        AutoRoute(page: WardRoundsRoute.page),
        AutoRoute(page: InpatientsListRoute.page),
        AutoRoute(page: DoctorPendingLabsRoute.page),
        AutoRoute(page: DoctorPendingImagingRoute.page),
        AutoRoute(page: DoctorPendingPrescriptionsRoute.page),
        AutoRoute(page: DoctorCompletedEncountersRoute.page),
        AutoRoute(page: ConsultationPaymentReportRoute.page),
        AutoRoute(page: EncounterEditHistoryDetailRoute.page),
        AutoRoute(page: DoctorTemplatesRoute.page),
        AutoRoute(page: DoctorProfileRoute.page),
        AutoRoute(
          page: DoctorCompletedEncounterViewRoute.page,
          children: [
            AutoRoute(page: CompletedEncounterSummaryTab.page, initial: true),
            AutoRoute(page: CompletedEncounterHistoryTab.page),
            AutoRoute(page: CompletedEncounterExaminationTab.page),
            AutoRoute(page: CompletedEncounterNotesTab.page),
            AutoRoute(page: CompletedEncounterDiagnosisTab.page),
            AutoRoute(page: CompletedEncounterLabsTab.page),
            AutoRoute(page: CompletedEncounterImagingTab.page),
            AutoRoute(page: CompletedEncounterPrescriptionsTab.page),
            AutoRoute(page: CompletedEncounterAppointmentsTab.page),
            AutoRoute(page: CompletedEncounterFollowUpTab.page),
          ],
        ),
        AutoRoute(
          page: DoctorEncounterViewRoute.page,
          children: [
            AutoRoute(page: DoctorEncounterHistoryTab.page, initial: true),
            AutoRoute(page: DoctorEncounterExaminationTab.page),
            AutoRoute(page: DoctorEncounterDiagnosisTab.page),
            AutoRoute(page: DoctorEncounterInvestigationsTab.page),
            AutoRoute(page: DoctorEncounterImagingTab.page),
            AutoRoute(page: DoctorEncounterSurgeryTab.page),
            AutoRoute(page: DoctorEncounterPrescriptionTab.page),
            AutoRoute(page: DoctorEncounterProceduresTab.page),
            AutoRoute(page: DoctorEncounterNotesTab.page),
            AutoRoute(page: DoctorEncounterAdmissionTab.page),
            AutoRoute(page: DoctorEncounterFollowUpTab.page),
          ],
        ),
        AutoRoute(
          page: InpatientPatientViewRoute.page,
          children: [
            AutoRoute(page: InpatientOverviewRoute.page, initial: true),
            AutoRoute(page: InpatientVitalsRoute.page),
            AutoRoute(page: InpatientMedicationsRoute.page),
            AutoRoute(page: InpatientIVRoute.page),
            AutoRoute(page: InpatientIORoute.page),
            AutoRoute(page: InpatientNotesRoute.page),
            AutoRoute(page: InpatientWoundAssessmentRoute.page),
            AutoRoute(page: InpatientWardRoundTab.page),
            AutoRoute(page: InpatientProceduresRoute.page),
            AutoRoute(page: InpatientCarePlanRoute.page),
            AutoRoute(page: InpatientMonitoringRoute.page),
            AutoRoute(page: InpatientLabResultsRoute.page),
            AutoRoute(page: InpatientAlertsRoute.page),
            AutoRoute(page: InpatientHandoverRoute.page),
          ],
        ),
        AutoRoute(page: PharmacyDashboardRoute.page),
        AutoRoute(page: PharmacyHeadDashboardRoute.page),
        AutoRoute(page: PharmacyReportsHubRoute.page),
        AutoRoute(page: PharmacySalesBreakdownRoute.page),
        AutoRoute(page: PharmacySalesBreakdownDetailRoute.page),
        AutoRoute(page: PharmacyInventoryValuationRoute.page),
        AutoRoute(page: MedicineInventoryRoute.page),
        AutoRoute(page: AddDrugRoute.page),
        AutoRoute(page: AddSupplierRoute.page),
        AutoRoute(page: AddBatchRoute.page),
        AutoRoute(
          path: 'pharmacy/batchespreview-ward-pricing/:id',
          page: BatchesPreviewWardPricingRoute.page,
        ),
        AutoRoute(page: StockTransferRoute.page),
        AutoRoute(page: CreateRequisitionRoute.page),
        AutoRoute(page: SupplyHistoryRoute.page),
        AutoRoute(
          path: 'pharmacy/dispense-history',
          page: DispenseHistoryRoute.page,
        ),
        AutoRoute(page: PharmacyLocationRoute.page),
        AutoRoute(page: PharmacyPOSRoute.page),
        AutoRoute(page: DispenseRoute.page),
        AutoRoute(
          path: 'pharmacy/medication-requests',
          page: MedicationRequestsRoute.page,
        ),
        AutoRoute(
          path: 'pharmacy/refill-requests',
          page: PharmacyRefillRequestsRoute.page,
        ),
        AutoRoute(page: WaitingPatientRoute.page),
        AutoRoute(page: PurchaseItemSalesRoute.page),
        AutoRoute(page: PurchasesInventoryRoute.page),
        AutoRoute(page: PurchasesAddItemRoute.page),
        AutoRoute(page: PurchasesAddSupplierRoute.page),
        AutoRoute(page: PurchasesAddPurchaseRoute.page),
        AutoRoute(page: PurchasesStockTransferRoute.page),
        AutoRoute(page: PurchasesTransferHistoryRoute.page),
        AutoRoute(page: PurchasesPurchaseHistoryRoute.page),
        AutoRoute(page: PurchasesLocationRoute.page),
        AutoRoute(page: PurchasesRequisitionHistoryRoute.page),
        AutoRoute(
          path: 'purchases/usage-history',
          page: PurchasesUsageHistoryRoute.page,
        ),
        AutoRoute(page: PurchasesDashboardRoute.page),
        // O&G (Obstetrics & Gynaecology)
        AutoRoute(page: ObstetricsDashboardRoute.page),
        AutoRoute(page: ObstetricsPatientSelectRoute.page),
        AutoRoute(page: ObstetricsPregnanciesListRoute.page),
        AutoRoute(page: InpatientBillsListRoute.page),
        AutoRoute(page: BillingWardInpatientsRoute.page),
        AutoRoute(page: AwaitingBillingClearanceRoute.page),
        AutoRoute(page: PatientBillingRoute.page),
        AutoRoute(page: PatientWalletHistoryRoute.page),
        AutoRoute(page: WardManagementRoute.page),
        AutoRoute(
          page: ObstetricsPregnancyViewRoute.page,
          children: [
            AutoRoute(page: ObstetricsPregnancyOverviewTab.page, initial: true),
            AutoRoute(page: ObstetricsAntenatalVisitsTab.page),
            AutoRoute(page: ObstetricsLabourDeliveryTab.page),
            AutoRoute(page: ObstetricsPostnatalTab.page),
          ],
        ),
        AutoRoute(page: ObstetricsAddPregnancyRoute.page),
        AutoRoute(page: ObstetricsAddAntenatalVisitRoute.page),
        AutoRoute(page: ObstetricsEditAntenatalVisitRoute.page),
        AutoRoute(page: ObstetricsAddLabourDeliveryRoute.page),
        AutoRoute(page: ObstetricsLabourDeliveryViewRoute.page),
        AutoRoute(page: ObstetricsAddPartogramEntryRoute.page),
        AutoRoute(page: ObstetricsAddBabyRoute.page),
        AutoRoute(page: ObstetricsEditBabyRoute.page),
        AutoRoute(page: ObstetricsRegisterBabyRoute.page),
        AutoRoute(page: ObstetricsPostnatalListRoute.page),
        AutoRoute(page: ObstetricsAddPostnatalVisitRoute.page),
        AutoRoute(page: ObstetricsGynaeProceduresRoute.page),
        AutoRoute(page: ObstetricsAddGynaeProcedureRoute.page),
        AutoRoute(page: ObstetricsEditGynaeProcedureRoute.page),
        // Laboratory (dynamic lab module)
        AutoRoute(page: LabDashboardRoute.page),
        AutoRoute(page: LabInvestigationsRoute.page),
        AutoRoute(page: LabConfigRoute.page),
        AutoRoute(page: LabCreateOrderRoute.page),
        AutoRoute(page: LabOrderDetailRoute.page),
        AutoRoute(page: LabResultEntryRoute.page),
        // Dialysis
        AutoRoute(page: DialysisDashboardRoute.page),
        AutoRoute(page: DialysisSelectPatientRoute.page),
        AutoRoute(page: DialysisPatientEncountersRoute.page),
        AutoRoute(page: DialysisCreateSessionRoute.page),
        AutoRoute(page: DialysisSessionDetailRoute.page),
        // Theatre
        AutoRoute(page: TheatreDashboardRoute.page),
        AutoRoute(page: TheatreScheduleFormRoute.page),
        AutoRoute(page: TheatreCaseDetailRoute.page),
        AutoRoute(page: TheatreRoomsRoute.page),
        // Radiology
        AutoRoute(page: RadiologyDashboardRoute.page),
        AutoRoute(page: RadiologyInvestigationsRoute.page),
        AutoRoute(page: RadiologyWorklistRoute.page),
        AutoRoute(page: RadiologyCreateRequestRoute.page),
        AutoRoute(page: RadiologyRequestDetailRoute.page),
        AutoRoute(page: RadiologyPatientHistoryRoute.page),
        // ── Accounts & Audit ───────────────────────────────────────────
        AutoRoute(page: AccountsDashboardRoute.page),
        AutoRoute(page: AccountsRevenueSummaryRoute.page),
        AutoRoute(page: AccountsDailyCollectionsRoute.page),
        AutoRoute(page: AccountsAgingReportRoute.page),
        AutoRoute(page: AccountsFinancialReportsHubRoute.page),
        AutoRoute(page: AccountsProfitLossRoute.page),
        AutoRoute(page: AccountsCashFlowRoute.page),
        AutoRoute(page: AccountsRevenueByServiceRoute.page),
        AutoRoute(page: AccountsRevenueByServiceDetailRoute.page),
        AutoRoute(page: AccountsExpenseVsBudgetRoute.page),
        AutoRoute(page: AccountsCollectionEfficiencyRoute.page),
        AutoRoute(page: AccountsPeriodComparisonRoute.page),
        AutoRoute(page: AccountsPaymentMixRoute.page),
        AutoRoute(page: AccountsAuditLogRoute.page),
        AutoRoute(page: AccountsComplianceRoute.page),
        AutoRoute(page: AccountsInvoiceChangesRoute.page),
        AutoRoute(page: AccountsLeakDetectionRoute.page),
        AutoRoute(page: AccountsStaffActivityRoute.page),
        AutoRoute(page: AccountsRefundHistoryRoute.page),
        AutoRoute(page: AccountsWalletsOverviewRoute.page),
        AutoRoute(page: AccountsDailyCashReconRoute.page),
        AutoRoute(page: AccountsBankReconRoute.page),
        AutoRoute(page: AccountsApprovalsRoute.page),
        AutoRoute(page: AccountsRefundRequestsRoute.page),
        AutoRoute(page: AccountsPeriodCloseRoute.page),
        AutoRoute(page: AccountsJournalEntriesRoute.page),
        AutoRoute(page: AccountsChartOfAccountsRoute.page),
        AutoRoute(page: AccountsBanksRoute.page),
        AutoRoute(page: ReceivablesAnalyticsRoute.page),
        // Store
        AutoRoute(page: StoreDashboardRoute.page),
        AutoRoute(page: StoreCategoriesRoute.page),
        AutoRoute(page: StoreItemsRoute.page),
        AutoRoute(page: StoreLocationsRoute.page),
        AutoRoute(page: StoreStockRoute.page),
        AutoRoute(page: StoreMovementsRoute.page),
        AutoRoute(page: StoreAnalyticsRoute.page),
        AutoRoute(page: StoreConsumablesCatalogRoute.page),
        AutoRoute(page: StoreConsumableAnalyticsRoute.page),
        AutoRoute(
          path: 'store/consumables/detail/:consumableId',
          page: StoreConsumableDetailRoute.page,
        ),
        AutoRoute(page: HelpCenterRoute.page),
        AutoRoute(page: SupportTicketDetailRoute.page),
        AutoRoute(page: StaffChatRoute.page),
        AutoRoute(page: StaffChatThreadRoute.page),
        // HMO
        AutoRoute(page: HmoListRoute.page),
        AutoRoute(page: HmoDetailRoute.page),
        AutoRoute(page: HmoFormRoute.page),
        AutoRoute(page: HmoServicePricingRoute.page),
      ],
    ),

    // patient form is shown separately (modal/push)
  ];
}
