import 'package:auto_route/auto_route.dart';
import 'package:helty/app_router.gr.dart';
import 'package:helty/src/core/guards/auth_guard.dart';

@AutoRouterConfig(replaceInRouteName: 'Screen|Page,Route')
class AppRouter extends RootStackRouter {
  @override
  RouteType get defaultRouteType => RouteType.material();

  @override
  List<AutoRoute> get routes => [
    // ── Auth routes (no guard) ───────────────────────────────────────
    AutoRoute(page: LoginRoute.page, initial: true),
    AutoRoute(page: RegisterRoute.page),
    AutoRoute(page: ForgotPasswordRoute.page),
    AutoRoute(page: ResetPasswordRoute.page),

    // ── Protected shell ──────────────────────────────────────────────
    AutoRoute(
      page: HomeRoute.page,
      guards: [const AuthGuard()],
      children: [
        AutoRoute(page: CMDDashboardRoute.page, initial: true),
        AutoRoute(page: CMDHospitalOverviewRoute.page),
        AutoRoute(page: CMDFinancialCommandRoute.page),
        AutoRoute(page: CMDStaffOversightRoute.page),
        AutoRoute(page: CMDBedsFacilitiesRoute.page),
        AutoRoute(page: CMDLabMonitoringRoute.page),
        AutoRoute(page: CMDAlertsIncidentsRoute.page),
        AutoRoute(page: CMDReportsAnalyticsRoute.page),
        AutoRoute(page: CMDAuditComplianceRoute.page),
        AutoRoute(page: CMDCommunicationCenterRoute.page),
        AutoRoute(page: CMDPatientExperienceRoute.page),
        AutoRoute(page: CMDSystemControlRoute.page),
        AutoRoute(page: FrontDeskDashboardRoute.page),
        AutoRoute(page: PatientListRoute.page),
        AutoRoute(page: PatientFormRoute.page),
        AutoRoute(page: AppointmentListRoute.page),
        AutoRoute(page: TodayPatientsRoute.page),
        AutoRoute(page: PendingBillsRoute.page),
        AutoRoute(page: EnlistServiceRoute.page),
        AutoRoute(page: RenderServiceRoute.page),
        AutoRoute(page: ViewServiceRoute.page),
        // helper screens for creating new entities
        AutoRoute(page: AddServiceRoute.page),
        AutoRoute(page: AddCategoryRoute.page),
        AutoRoute(page: AddDepartmentRoute.page),
        AutoRoute(page: RegisterRoute.page),
        AutoRoute(page: EnlistPaitientRoute.page),
        AutoRoute(page: NewAppointmentRoute.page),
        AutoRoute(page: NotAvailableRoute.page),

        AutoRoute(page: NewPatientRoute.page),
        AutoRoute(page: BillingDashboardRoute.page),
        AutoRoute(page: TransactionsRoute.page),
        AutoRoute(page: SystemSetupRoute.page),
        AutoRoute(page: BankManagementRoute.page),
        AutoRoute(page: NursesDashboardRoute.page),
        AutoRoute(page: WaitingPatientsRoute.page),
        AutoRoute(page: ConsultingRoomsRoute.page),
        AutoRoute(page: DoctorDashboardRoute.page),
        AutoRoute(page: DoctorOutpatientListRoute.page),
        AutoRoute(page: DoctorWalkInQueueRoute.page),
        AutoRoute(page: WardRoundsRoute.page),
        AutoRoute(page: InpatientsListRoute.page),
        AutoRoute(page: DoctorPendingLabsRoute.page),
        AutoRoute(page: DoctorPendingImagingRoute.page),
        AutoRoute(page: DoctorPendingPrescriptionsRoute.page),
        AutoRoute(page: DoctorCompletedEncountersRoute.page),
        AutoRoute(page: DoctorTemplatesRoute.page),
        AutoRoute(page: DoctorProfileRoute.page),
        AutoRoute(
          page: DoctorCompletedEncounterViewRoute.page,
          children: [
            AutoRoute(page: CompletedEncounterSummaryTab.page, initial: true),
            AutoRoute(page: CompletedEncounterHistoryTab.page),
            AutoRoute(page: CompletedEncounterExaminationTab.page),
            AutoRoute(page: CompletedEncounterNotesTab.page),
            AutoRoute(page: CompletedEncounterDiagnosisTab.page),
            AutoRoute(page: CompletedEncounterFollowUpTab.page),
          ],
        ),
        AutoRoute(
          page: DoctorEncounterViewRoute.page,
          children: [
            AutoRoute(page: DoctorEncounterHistoryTab.page, initial: true),
            AutoRoute(page: DoctorEncounterExaminationTab.page),
            AutoRoute(page: DoctorEncounterDiagnosisTab.page),
            AutoRoute(page: DoctorEncounterInvestigationsTab.page),
            AutoRoute(page: DoctorEncounterImagingTab.page),
            AutoRoute(page: DoctorEncounterPrescriptionTab.page),
            AutoRoute(page: DoctorEncounterProceduresTab.page),
            AutoRoute(page: DoctorEncounterNotesTab.page),
            AutoRoute(page: DoctorEncounterAdmissionTab.page),
            AutoRoute(page: DoctorEncounterFollowUpTab.page),
          ],
        ),
        AutoRoute(
          page: InpatientPatientViewRoute.page,
          children: [
            AutoRoute(page: InpatientOverviewRoute.page, initial: true),
            AutoRoute(page: InpatientVitalsRoute.page),
            AutoRoute(page: InpatientMedicationsRoute.page),
            AutoRoute(page: InpatientIVRoute.page),
            AutoRoute(page: InpatientIORoute.page),
            AutoRoute(page: InpatientNotesRoute.page),
            AutoRoute(page: InpatientWardRoundTab.page),
            AutoRoute(page: InpatientProceduresRoute.page),
            AutoRoute(page: InpatientCarePlanRoute.page),
            AutoRoute(page: InpatientMonitoringRoute.page),
            AutoRoute(page: InpatientLabResultsRoute.page),
            AutoRoute(page: InpatientAlertsRoute.page),
            AutoRoute(page: InpatientHandoverRoute.page),
          ],
        ),
        AutoRoute(page: PharmacyDashboardRoute.page),
        AutoRoute(page: MedicineInventoryRoute.page),
        AutoRoute(page: AddDrugRoute.page),
        AutoRoute(page: AddSupplierRoute.page),
        AutoRoute(page: AddBatchRoute.page),
        AutoRoute(page: StockTransferRoute.page),
        AutoRoute(page: CreateRequisitionRoute.page),
        AutoRoute(page: SupplyHistoryRoute.page),
        AutoRoute(page: PharmacyLocationRoute.page),
        AutoRoute(page: PharmacyPOSRoute.page),
        AutoRoute(page: DispenseRoute.page),
        AutoRoute(page: WaitingPatientRoute.page),
        // O&G (Obstetrics & Gynaecology)
        AutoRoute(page: ObstetricsDashboardRoute.page),
        AutoRoute(page: ObstetricsPatientSelectRoute.page),
        AutoRoute(page: ObstetricsPregnanciesListRoute.page),
        AutoRoute(page: InpatientBillsListRoute.page),
        AutoRoute(page: PatientBillingRoute.page),
        AutoRoute(page: WardManagementRoute.page),
        AutoRoute(
          page: ObstetricsPregnancyViewRoute.page,
          children: [
            AutoRoute(page: ObstetricsPregnancyOverviewTab.page, initial: true),
            AutoRoute(page: ObstetricsAntenatalVisitsTab.page),
            AutoRoute(page: ObstetricsLabourDeliveryTab.page),
            AutoRoute(page: ObstetricsPostnatalTab.page),
          ],
        ),
        AutoRoute(page: ObstetricsAddPregnancyRoute.page),
        AutoRoute(page: ObstetricsAddAntenatalVisitRoute.page),
        AutoRoute(page: ObstetricsEditAntenatalVisitRoute.page),
        AutoRoute(page: ObstetricsAddLabourDeliveryRoute.page),
        AutoRoute(page: ObstetricsLabourDeliveryViewRoute.page),
        AutoRoute(page: ObstetricsAddPartogramEntryRoute.page),
        AutoRoute(page: ObstetricsAddBabyRoute.page),
        AutoRoute(page: ObstetricsEditBabyRoute.page),
        AutoRoute(page: ObstetricsRegisterBabyRoute.page),
        AutoRoute(page: ObstetricsPostnatalListRoute.page),
        AutoRoute(page: ObstetricsAddPostnatalVisitRoute.page),
        AutoRoute(page: ObstetricsGynaeProceduresRoute.page),
        AutoRoute(page: ObstetricsAddGynaeProcedureRoute.page),
        AutoRoute(page: ObstetricsEditGynaeProcedureRoute.page),
        // Laboratory (dynamic lab module)
        AutoRoute(page: LabDashboardRoute.page),
        AutoRoute(page: LabConfigRoute.page),
        AutoRoute(page: LabCreateOrderRoute.page),
        AutoRoute(page: LabOrderDetailRoute.page),
        AutoRoute(page: LabResultEntryRoute.page),
        // Radiology
        AutoRoute(page: RadiologyDashboardRoute.page),
        AutoRoute(page: RadiologyWorklistRoute.page),
        AutoRoute(page: RadiologyCreateRequestRoute.page),
        AutoRoute(page: RadiologyRequestDetailRoute.page),
        AutoRoute(page: RadiologyPatientHistoryRoute.page),
        // Store
        AutoRoute(page: StoreDashboardRoute.page),
        AutoRoute(page: StoreCategoriesRoute.page),
        AutoRoute(page: StoreItemsRoute.page),
        AutoRoute(page: StoreLocationsRoute.page),
        AutoRoute(page: StoreStockRoute.page),
        AutoRoute(page: StoreMovementsRoute.page),
        AutoRoute(page: StoreAnalyticsRoute.page),
      ],
    ),

    // patient form is shown separately (modal/push)
  ];
}
